### ISSUE TITLE
Error regardin style_asphere.h

### ISSUE THREAD

**Issue by nahidrahmati** [yixiangD/coagulation_cascade#1]
Hello, 
I am trying to compile this code. However, in the first step, (make in src folder), I am receiving this error: 
fatal error: style_asphere.h: No such file or directory

which is required to make following files: 
g++: error: atom.o: No such file or directory
g++: error: input.o: No such file or directory
g++: error: update.o: No such file or directory
g++: error: modify.o: No such file or directory
g++: error: output.o: No such file or directory
g++: error: domain.o: No such file or directory
g++: error: force.o: No such file or directory

Can you please update this required file in this repo?

**Comment by yixiangD** [comment]
Added! Thanks. Please check again.

**Comment by yixiangD** [comment]
resolved.

**Comment by yixiangD** [comment]
resolved.
